# change according to system and gurobi version

GUROBI_PATH = /Library/gurobi1000
HOST_ARCH = macos_universal2

# The following is for Linux
GUROBI_PATH =  /home/duttaso/Gurobi_installation/gurobi1001
HOST_ARCH =  linux64
